#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi



# Wallpaper
xwallpaper --zoom $HOME/.local/wallpapers/kali-ascii-16x9.png

# Compositor
picom --experimental-backends &

if [ "$(cat .local/n_monitors)" = "2" ]; then
    dual_monitor.sh
    qtile start -c ~/.config/qtile/dual_monitor.py
else
    qtile start -c ~/.config/qtile/single_monitor.py
fi

