colors:
  bright:
    black: '0x808080'
    blue: '0x0066ff'
    cyan: '0x00ffff'
    green: '0x33ff00'
    magenta: '0xcc00ff'
    red: '0xfe0100'
    white: '0xFFFFFF'
    yellow: '0xfeff00'
  cursor:
    cursor: '0xffffff'
    text: '0xF81CE5'
  normal:
    black: '0x000000'
    blue: '0x0066ff'
    cyan: '0x00ffff'
    green: '0x33ff00'
    magenta: '0xcc00ff'
    red: '0xfe0100'
    white: '0xd0d0d0'
    yellow: '0xfeff00'
  primary:
    background: '0x000000'
    foreground: '0xffffff'
  transparent_background_colors: true
