colors:
  bright:
    black: '0x000000'
    blue: '0x0000bb'
    cyan: '0x00bbbb'
    green: '0x00bb00'
    magenta: '0xbb00bb'
    red: '0xbb0000'
    white: '0xbbbbbb'
    yellow: '0xbbbb00'
  cursor:
    cursor: '0xffffff'
    text: '0xaaaaaa'
  normal:
    black: '0x000000'
    blue: '0x0000bb'
    cyan: '0x00bbbb'
    green: '0x00bb00'
    magenta: '0xbb00bb'
    red: '0xbb0000'
    white: '0xbbbbbb'
    yellow: '0xbbbb00'
  primary:
    background: '0x333333'
    foreground: '0xdddddd'
  transparent_background_colors: true
